spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aaa
    username: "root"
    password: "0254"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect   # MySQL 8.0 Dialect 명시
        connection:
          readOnly: true    # DB를 읽기 전용으로 설정
    open-in-view: false       # Open Session in View 비활성화